version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: ba2re/flask_crud_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgre sql://postgres:postgres@flask_db:5432/postgres 
    depends_on:
      - flask_db
    
  flask_db:
    container_name: flask_db
    image: postgres:12 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB= 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  {}




     

